services:
  mysql:
    container_name: template-mysql
    image: mysql:8.4.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: template
      TZ: Asia/Seoul
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/var/lib/mysql:/var/lib/mysql # data
      - ./docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d # config
      - ./docker/mysql/init:/docker-entrypoint-initdb.d # init
  redis:
    container_name: template-redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
