spring:
  config:
    import:
      - db-core.yml
      - core-event.yml
      - logging.yml
      - monitoring.yml

  task:
    execution:
      thread-name-prefix: "worker-task-"
      pool:
        core-size: 10
        max-size: 10
        queue-capacity: 10000
      shutdown:
        await-termination: true
        await-termination-period: 10000

---
spring:
  config.activate.on-profile: local

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092

---
spring:
  config.activate.on-profile: local-dev

---
spring:
  config.activate.on-profile: dev

---
spring:
  config.activate.on-profile: live

