spring:
  kafka:
    bootstrap-servers: {KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: -1
      retries: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        min.insync.replicas: 2
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: worker
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        auto.offset.reset: none
    listener:
      type: batch
      ack-mode: batch

app:
  event:
    post-like:
      topic-name: ${POST_LIKE_TOPIC_NAME:core.post-like}

---
spring:
  config.activate.on-profile: local
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
